"[gtest] Upgrade to 1.10.0. Contributes to JB#54442"
sailfishos/gtest pull request #3
Opened 2021-05-27 14:27 UTC by pbmedved

2021-05-27 15:05 UTC, okodron reviewed
Better to use `%autosetup` instead of `%setup`

2021-05-31 11:41 UTC, okodron requested changes

2021-05-31 11:41 UTC, okodron commented on rpm/gtest.spec
> +%autosetup -q -n %{name}-%{version}/%{name}
In such case you need to pass additional argument for patch:
```suggestion
%autosetup -p1 -n %{name}-%{version}/%{name}
```
And you don't need any more to specify all the patches explicitly: https://rpm.org/user_doc/autosetup.html

2021-05-31 16:00 UTC, okodron reviewed
As the main package is called `gtest` it sounds logical to rename `libgmock` sub-package to `gmock`. It will also comply with Fedora's version.

2021-06-01 13:42 UTC, okodron commented on rpm/gtest.spec
>  %files -n libgmock
Should be also renamed to `gmock`.

2021-06-01 14:19 UTC, pbmedved commented on rpm/gtest.spec
>  %files -n libgmock
done

2021-06-01 15:08 UTC, okodron approved these changes
LGTM

2021-06-18 11:53 UTC, pvuorela commented
No objections on that gmock renaming per se, especially if Fedora isn't using the "lib" prefix, but looks like sailfish-browser is depending on libgmock-devel. Need to either fix that at the same time or then provide also the earlier name. Simplest might be to do the renaming separately.

Btw looks like there also 1.11.0 available now.

2021-06-18 14:41 UTC, okodron commented
Can you change the MR title? Cause it's no more 1.10.0 upgrade...

2021-06-18 14:45 UTC, okodron requested changes

2021-06-18 14:45 UTC, okodron commented on rpm/gtest.spec
> +%license ./LICENSE
Just this:
```suggestion
%license LICENSE
```

2021-06-18 14:45 UTC, okodron commented on rpm/gtest.spec
> +%license ./LICENSE
```suggestion
%license LICENSE
```

2021-06-18 15:55 UTC, okodron approved these changes

2021-06-21 12:15 UTC, pvuorela commented
Looks nicely simple update now, but for making sure I tried doing a test build in OBS. However this happened:
```
[   26s] CMake Error at googlemock/CMakeLists.txt:43 (project):
[   26s]   VERSION "1.8.1+1.10.0.20210618151355.1.g0b64396" format invalid.
```

The .spec has sed call for replacing the version. Looks suspicious and would expect it's not needed.

2021-06-21 15:10 UTC, okodron commented
> Looks nicely simple update now, but for making sure I tried doing a test build in OBS. However this happened:
> 
> ```
> [   26s] CMake Error at googlemock/CMakeLists.txt:43 (project):
> [   26s]   VERSION "1.8.1+1.10.0.20210618151355.1.g0b64396" format invalid.
> ```
> 
> The .spec has sed call for replacing the version. Looks suspicious and would expect it's not needed.

Can it happen due to the "not-so-expected" version from your local build? I mean whether it works with `1.11.1` version set via tag?

2021-06-22 05:15 UTC, martyone commented
The .spec shouldn't use `%{version}` as is. It should do something like https://github.com/sailfishos/libqofono/blob/master/rpm/libqofono-qt5.spec#L60 to allow test builds from untagged revisions.

2021-06-22 06:59 UTC, pvuorela commented
Yes, something like that might do the trick. Then again grepping from the sources there's already
`CMakeLists.txt:set(GOOGLETEST_VERSION 1.11.0)` and don't see why we should be overriding that in the build.

2021-06-22 07:16 UTC, martyone commented
I see two issues:
1. unnecessary modifying sources during build
2. hardcoding (duplicating) version in sources

I would omit setting the value in CMakeLists.txt and instead assert there that it was provided on cmake command line (possibly falling back to some default like 1.0 for convenience).

2021-06-22 07:32 UTC, okodron commented
> Yes, something like that might do the trick. Then again grepping from the sources there's already
> `CMakeLists.txt:set(GOOGLETEST_VERSION 1.11.0)` and don't see why we should be overriding that in the build.

Indeed: version patching seems like an unnecessary step at least now.

2021-06-22 07:34 UTC, okodron requested changes
@pbmedved, please, drop the version patching with sed.

2021-06-22 11:02 UTC, pbmedved commented
It should build normally now.

2021-06-22 11:07 UTC, pvuorela commented
Better but then hit another problem:
```
[   41s] RPM build errors:
[   41s]     File not found: /home/abuild/rpmbuild/BUILDROOT/gtest-1.8.1+1.10.0.20210622105856.1.ga3229a7-1.2.1.jolla.i386/usr/lib/libgtest.so.1.8.1+1.10.0.20210622105856.1.ga3229a7
[   41s]     File not found: /home/abuild/rpmbuild/BUILDROOT/gtest-1.8.1+1.10.0.20210622105856.1.ga3229a7-1.2.1.jolla.i386/usr/lib/libgtest_main.so.1.8.1+1.10.0.20210622105856.1.ga3229a7
```

The %files section in main an gmock has %{version} appended. That's just silly, replace with so.*

2021-06-22 11:33 UTC, okodron reviewed
Looks better now.

2021-06-22 11:39 UTC, pvuorela commented
Now builds and libphonenumber on top of this. Browser on obs didn't like having a choice on gmock devel for the old and new names, but I'll do a local build to be on the safe side.

2021-06-22 11:54 UTC, pvuorela commented
And local build fine. LGTM!

2021-06-22 11:54 UTC, merged

2021-06-22 12:13 UTC, pvuorela commented
Didn't fully work. https://github.com/sailfishos/gtest/pull/4/files